### ISSUE TITLE
Error: object 'isBIP' not found

### ISSUE THREAD

**Issue by gjm112** [beanumber/openWAR#103]
I'm getting this error when I run makeWAR.  I don't have time to look into it now, but thought I would make a note of it.

**Comment by gjm112** [comment]
I think this is a dplyr issue with filter.  But I can't seem to fix it.

**Comment by gjm112** [comment]
I'm trying to update openWAR for 2016, but I keep getting this error.  I have no idea how to fix it.

**Comment by beanumber** [comment]
@gjm112 Can you post a MWE and your session info?
