### ISSUE TITLE
R Version

### ISSUE THREAD

**Issue by stevebit** [beanumber/openWAR#105]
Hi, 

What's the latest version of R that the openWARS package works for.  I've tried it for multiple version of R going back to 2.15.3 to 3.3.2.  I keep getting the following error.  

"is not available (for R version 3.0.3)"

Thanks

**Comment by beanumber** [comment]
@stevebit What are you running in order to generate that error? Is it this:
```
> install.packages("openWAR")
Installing package into ‘/home/bbaumer/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘openWAR’ is not available (for R version 3.3.2)
```
Note that `openWAR` is not on CRAN so you have to use the `install_github()` function from the `devtools` package in order to install it. Please see the [README](https://github.com/beanumber/openWAR).

**Comment by stevebit** [comment]
Hi Ben,

I'm running the following.  Thanks for your help.  Great package by the way.

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252
 LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] httr_1.2.1      R6_2.2.0        rsconnect_0.7   tools_3.3.2
withr_1.0.2     curl_2.3        memoise_1.0.0   git2r_0.18.0
 [9] digest_0.6.11   devtools_1.12.0
> devtools::install_github("beanumber/openWAR")
*Error in curl::curl_fetch_disk(url, x$path, handle = handle) : *
*  Couldn't resolve host name*

**Comment by beanumber** [comment]
Hmm...it sounds like switching to Google DNS might solve your problem:

https://github.com/jeroenooms/curl/issues/72
https://github.com/hadley/devtools/issues/877
