### ISSUE TITLE
Still having trouble installing Sxslt package on github to be able to install openWar

### ISSUE THREAD

**Issue by puvrocks27** [beanumber/openWAR#107]
I am trying to use openWar to do some sequential testing with baseball data, and I have gone through the steps in the Readme section to install the Sxslt package, which is necessary to install the openWar package through github. However, it gives me this same error in Rstudio every time. 

Downloading GitHub repo omegahat/Sxslt@master
from URL https://api.github.com/repos/omegahat/Sxslt/zipball/master
Installing Sxslt
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Pravin/AppData/Local/Temp/Rtmp2TlkbH/devtools2b28171a621b/omegahat-Sxslt-0407182"  \
  --library="C:/Users/Pravin/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'Sxslt' ...
Please define LIB_XSLT
Warning: running command 'sh ./configure.win' had status 1
ERROR: configuration failed for package 'Sxslt'
* removing 'C:/Users/Pravin/Documents/R/win-library/3.4/Sxslt'
Installation failed: Command failed (1)

I am running in windows and I am not sure what the issue is. The command I am using is as follows:

devtools::install_github("omegahat/Sxslt")

**Comment by davidbmitchell** [comment]
I still don't think there is a way to install on Windows. But I am not 100% on that. The particular problem you are running into is that `LIB_XSLT` has not been defined. You could define this by:
```
Sys.setenv(LIB_XLST= "C:/path/to/libxslt")
```
I know there are ports for  `libxml2` and `libxlst` provided by [Igor Zlatković](https://www.zlatkovic.com/libxml.en.html) but I was not able to get them to work. It looks like [MSYS2](http://www.msys2.org/) could also be an option but the only windows computer I have is at work and they wouldn't let me install this because I would need administrator access.

**Comment by beanumber** [comment]
@puvrocks27 Did you try this:

```
require(devtools)
install_github("Sxslt", "cboettig")
```

**Comment by puvrocks27** [comment]
@beanumber  I tried this and still didnt work out.

**Comment by puvrocks27** [comment]
@davidbmitchell I tried this first command and didnt work out. I also tried installing MSYS2 and I still get the same errors.

**Comment by davidbmitchell** [comment]
Because you are Windows you're probably out of luck. I never was able to get it working on Windows. I think you would probably have to port the libraries to Windows yourself and honestly I don't even know where to begin there

**Comment by davidbmitchell** [comment]
The easiest workaround at this point for Windows is setting up a Linux virtual machine using VirtualBox or something similar

**Comment by znmeb** [comment]
@puvrocks27 @davidbmitchell On Windows 10 Pro you've got a few options:

1. Command line R should run in the Windows Linux subsystem. 
2. Docker for Windows plue Rocker / RStudio server - this is Debian Lunux under the hood.
3. A full Linux VM, again running RStudio. Frankly, I think that's overkill; if you're really that into the Linux desktop (as I am) you should just dual-boot your machine. ;-)
4. Rocker / RStudio or openCPU in the cloud.

Long-term, I'd like to see a project to merge pitchRx and openWAR, using tidyverse for data management. I think all the MLB site code in pitchRx works, although I haven't tried it recently. There would be some modest refactoring needed to catch up with dplyr 0.7.0  / tidy evaluation, but that's clearly worth the effort if people are going to do serious work with MLB data.

**Comment by puvrocks27** [comment]
@davidbmitchell @beanumber @znmeb I have access to a lab with a Mac so I am going to try installing the package there. I was previously scraping urls for line scores of many games, which is the only data I need right now, but openWar seems to have a much more efficient way of getting many games. So we will see if it works on a Mac.

**Comment by davidbmitchell** [comment]
@znmeb I'm working on refactoring the code to work with tidyeval. I think I've found the pattern the causing it to break some openWAR functions. Its just going on a little slower than I like because I'm also in the process of renovating my new house.
