### ISSUE TITLE
2016 data returns error when running makeWAR.  

### ISSUE THREAD

**Issue by gjm112** [beanumber/openWAR#116]
Example: 
library(openWAR)
load("~/Dropbox/openWARData/data/MLBAM2016.rda")
openWARplays2016 <- makeWAR(MLBAM2016)

 Error in filter_impl(.data, quo) : 
  Evaluation error: object 'isBIP' not found. 

This only happens for 2016.  All other years work.

**Comment by beanumber** [comment]
Confirmed. Not sure if [this](https://github.com/beanumber/openWARData/issues/12) is *the* problem, but it's *a* problem.
