### ISSUE TITLE
Error in rm.vec["end1B"] = subset(rm.df, end == "1B")$id :    replacement has length zero

### ISSUE THREAD

**Issue by beanumber** [beanumber/openWAR#22]
WHY?!?!

**Comment by Timsie** [comment]
The errors don't disappear after sourcing GameDay.R for me :(  I also get another error: 

`In readData.gameday(gd) : NAs introduced by coercion
Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "NULL"`

This was when running games = getData(start = "2014-05-21", end = "2014-05-21").  Any ideas?

**Comment by beanumber** [comment]
I know this must be related to the transition from `plyr` to `dplyr`, and that might explain the error you are seeing with `filter`. I haven't yet been able to track down the other bug yet. 

Very frustrating.

**Comment by beanumber** [comment]
For now, you can use the v0.1 release until I fix this:

https://github.com/beanumber/openWAR/releases/tag/v0.1

**Comment by Timsie** [comment]
Thanks!  For now I'm just using GameDay.R for my needs.  I've stripped out a lot ot help in my learning process...

**Comment by gjm112** [comment]
Ben, 

I get this same problem.  And when I source GameDay.R I get no errors.  I have NO IDEA what would cause this.  

Cheers, 
Greg

**Comment by znmeb** [comment]
I'm seeing this when I do `devtools::install_github('beanumber/openWAR', build_vignettes=TRUE)` as well.

```
* creating vignettes ... ERROR
Loading required package: openWAR
gid_2012_08_12_atlmlb_nynmlb_1
Loading required package: mosaic
Loading required package: car
Loading required package: dplyr

Attaching package: 'dplyr'

The following object is masked from 'package:stats':

    filter

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Loading required package: lattice
Loading required package: ggplot2

Attaching package: 'mosaic'

The following objects are masked from 'package:dplyr':

    count, do, tally

The following object is masked from 'package:car':

    logit

The following objects are masked from 'package:stats':

    D, IQR, binom.test, cor, cov, fivenum, median, prop.test,
    quantile, sd, t.test, var

The following objects are masked from 'package:base':

    max, mean, min, prod, range, sample, sum

Loading required package: Sxslt
Loading required package: stringr
Error in rm.vec["end1B"] = subset(rm.df, end == "1B")$id : 
  replacement has length zero
Loading required package: RCurl
Loading required package: bitops
gid_2013_05_14_atlmlb_arimlb_1
Error in rm.vec["end2B"] = subset(rm.df, end == "2B")$id : 
  replacement has length zero
gid_2013_05_14_bosmlb_tbamlb_1
Warning in readData.gameday(gd) : NAs introduced by coercion
Error in rm.vec["end1B"] = subset(rm.df, end == "1B")$id : 
  replacement has length zero
gid_2013_05_14_chamlb_minmlb_1
Warning in readData.gameday(gd) : NAs introduced by coercion
Error in rm.vec["end1B"] = subset(rm.df, end == "1B")$id : 
  replacement has length zero
gid_2013_05_14_cinmlb_miamlb_1
Error in rm.vec["end2B"] = subset(rm.df, end == "2B")$id : 
  replacement has length zero
gid_2013_05_14_clemlb_phimlb_1
Error in rm.vec["end1B"] = subset(rm.df, end == "1B")$id : 
  replacement has length zero
gid_2013_05_14_colmlb_chnmlb_1
Error in rm.vec["end2B"] = subset(rm.df, end == "2B")$id : 
  replacement has length zero
gid_2013_05_14_houmlb_detmlb_1
Warning in readData.gameday(gd) : NAs introduced by coercion
Error in rm.vec["end1B"] = subset(rm.df, end == "1B")$id : 
  replacement has length zero
gid_2013_05_14_kcamlb_anamlb_1
Warning in readData.gameday(gd) : NAs introduced by coercion
Error in rm.vec["end1B"] = subset(rm.df, end == "1B")$id : 
  replacement has length zero
gid_2013_05_14_milmlb_pitmlb_1
Error in rm.vec["end1B"] = subset(rm.df, end == "1B")$id : 
  replacement has length zero
gid_2013_05_14_nynmlb_slnmlb_1
Error in rm.vec["end1B"] = subset(rm.df, end == "1B")$id : 
  replacement has length zero
gid_2013_05_14_sdnmlb_balmlb_1
Warning in readData.gameday(gd) : NAs introduced by coercion
Error in rm.vec["end1B"] = subset(rm.df, end == "1B")$id : 
  replacement has length zero
gid_2013_05_14_seamlb_nyamlb_1
Warning in readData.gameday(gd) : NAs introduced by coercion
Error in rm.vec["end1B"] = subset(rm.df, end == "1B")$id : 
  replacement has length zero
gid_2013_05_14_sfnmlb_tormlb_1
Warning in readData.gameday(gd) : NAs introduced by coercion
Error in rm.vec["end2B"] = subset(rm.df, end == "2B")$id : 
  replacement has length zero
gid_2013_05_14_texmlb_oakmlb_1
Warning in readData.gameday(gd) : NAs introduced by coercion
Error in rm.vec["end1B"] = subset(rm.df, end == "1B")$id : 
  replacement has length zero
gid_2013_05_14_wasmlb_lanmlb_1
Error in rm.vec["end1B"] = subset(rm.df, end == "1B")$id : 
  replacement has length zero
Quitting from lines 53-55 (intro.Rmd) 
Error: processing vignette 'intro.Rmd' failed with diagnostics:
no applicable method for 'filter_' applied to an object of class "NULL"
Execution halted
Error: Command failed (1)
> 
```

**Comment by obarisk** [comment]
please check the getRunnerMovement function within R/GameDay.R
use namespace predicate before summarize and group_by
or full remove plyr in the package ( it reqires regenerating namespace file )

use predicate should look like this
rm.df <- dplyr::summarize(dplyr:;group_by(rm.df, id), start=min(start), end=max(end))

plyr::summarize will not retain column for grouping.

**Comment by znmeb** [comment]
@obarisk Does your fork have this fix?

**Comment by obarisk** [comment]
Yes, I'll send a pull request after checking my code.

**Comment by znmeb** [comment]
@obarisk Thanks!!

**Comment by gjm112** [comment]
This is a huge help.

On Wed, May 13, 2015 at 6:19 PM, 鐘翊修 <notifications@github.com> wrote:

> Yes, I'll send a pull request after checking my code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beanumber/openWAR/issues/22#issuecomment-101846076>.
>



-- 
Gregory J. Matthews, Ph.D.
Assistant Professor
Department of Mathematics
Loyola University Chicago
E-mail: gjm112 -at- gmail.com
Blog: StatsInTheWild.com
Twitter: @StatsInTheWild <http://www.twitter.com/StatsInTheWild>
Twitter: @StatsClass <http://www.twitter.com/statsclass>

**Comment by beanumber** [comment]
I think commit 8468be0 from @obarisk fixed this. 

@gjm112:  can you confirm and close the issue?

**Comment by znmeb** [comment]
The vignette builds successfully thanks to commit 8468be0 as well.

**Comment by gjm112** [comment]
Ben did you close this already or did you close a different item?

On Thu, May 14, 2015 at 12:19 PM, M. Edward (Ed) Borasky <
notifications@github.com> wrote:

> The vignette builds successfully thanks to commit 8468be0
> <https://github.com/beanumber/openWAR/commit/8468be080cc15e0983d14bae7300e5874d98f3e8>
> as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beanumber/openWAR/issues/22#issuecomment-102107056>.
>



-- 
Gregory J. Matthews, Ph.D.
Assistant Professor
Department of Mathematics
Loyola University Chicago
E-mail: gjm112 -at- gmail.com
Blog: StatsInTheWild.com
Twitter: @StatsInTheWild <http://www.twitter.com/StatsInTheWild>
Twitter: @StatsClass <http://www.twitter.com/statsclass>

**Comment by beanumber** [comment]
@gjm112 I was hoping you could confirm that the bug is fixed and then close this issue -- which is still open (but I believe can be closed).

**Comment by gjm112** [comment]
I just checked this.  This works now: 

![screen shot 2015-05-18 at 1 03 41 pm](https://cloud.githubusercontent.com/assets/1152165/7686836/581d27a8-fd5e-11e4-937c-aa6dca1c7171.png)
