### ISSUE TITLE
Include a link to the openWAR arXiv paper in the documentation

### ISSUE THREAD

**Issue by znmeb** [beanumber/openWAR#26]
In 'DESCRIPTION' there's this phrase:

"Those interested in the modeling choices that we have made in our computation of openWAR should consult our paper on the arXiv on that subject."

I couldn't find a link anywhere in the documentation to the paper. So I had to do a search (Yahoo, "openWAR arXiv" did the trick.)

http://arxiv.org/abs/1312.7158

Seems like that link should be somewhere in the documentation but I couldn't find it.

**Comment by beanumber** [comment]
So added.
