### ISSUE TITLE
Installing Sxslt on Windows

### ISSUE THREAD

**Issue by beanumber** [beanumber/openWAR#31]
Obviously, the best solution is to remove Windows. :)

My general thinking on this is that it is an issue between `Sxslt` and `Windows`, which are two pieces of software that we don't control. Therefore, there's really not much we can do about these compatibility issues, other than to point people in the right direction for solving them on their own. 

Please see the [official `Sxslt` documentation](http://www.omegahat.org/Sxslt/) for instructions about installing on Windows. Apparently there is also a GitHub version that you may have better luck installing from source. 

```
require(devtools)
install_github("Sxslt", "cboettig")
```

That being said, I'll concede that if a huge proportion of the people who want to run our package can't install it, then this is a problem for us. 

At some point, it might make sense to consider removing the `Sxslt` dependency entirely. The advantage of using XSLT is that it enables the GameDay files to be parsed logically in one command. By doing this we are keeping our package lightweight and using the right tool for the job. The fact that this doesn't work seamlessly on Windows is (in my view) a bug in Windows. 

Migrating to @cpsievert 's `XML2R` package is a possible solution.

**Comment by hafen** [comment]
I had a lot of trouble getting it installed on os x as well.  Given the last time that package was updated and the fact that it's a very non-standard install (not CRAN or github, plus system dependencies that don't like to compile correctly all the time), I would give a +1 for finding an alternative package that does the same job and that is easy to install.  I'd argue that the possibility of having to add a few extra lines of code on the developer's part to work with a different package vs. people not using the package because they can't install it is a good choice.

**Comment by znmeb** [comment]
I too have pretty much punted on Windows. I'm about to release a Docker image built on Fedora 22 just so all my users have the same software. ;-) 

If you want to go the Docker route you can build on "Rocker" (Debian base) or my "OSJourno" images (Fedora base). Either one will work in Boot2Docker on Windows or MacOS X or "native" in a modern Linux workstation (Ubuntu/Mint, openSUSE or Fedora, for example).

**Comment by pssguy** [comment]
"That being said, I'll concede that if a huge proportion of the people who want to run our package can't install it, then this is a problem for us."

I'm a 100%  Windows user. The other installation suggestion also failed

" The fact that this doesn't work seamlessly on Windows is (in my view) a bug in Windows." 

Hopefully, you have submitted a bug report and they have dropped everything else to solve it :)

**Comment by beanumber** [comment]
That would be nice! It's bug from my point-of-view, but from theirs, it's a feature! 

But seriously, we'll look into more cross-platform friendly alternatives for the next version.

**Comment by znmeb** [comment]
I have a Docker image build in the works that will include openWAR and its dependencies. It should work via Boot2Docker on Windows or Mac or via normal Docker on Linux or "in the cloud". ETA mid-day Pacific Time tomorrow.

**Comment by beanumber** [comment]
This is a potential alternative to `Sxslt`, but it sounds like it still has similar external dependencies, so I'm not sure that it solves anything for Windows users.

https://github.com/hrbrmstr/xslt

**Comment by znmeb** [comment]
How hard would it be for you to replace the GameDay Sxslt functionality with the code from pitchRx? It also has the advantage of using SQLite or MySQL to maintain the data!
