### ISSUE TITLE
figure out what to do with data files

### ISSUE THREAD

**Issue by beanumber** [beanumber/openWAR#38]
Move bigger data sets to `openWARData` and update vignettes.

**Comment by beanumber** [comment]
I have added some stuff in `data-raw/` that will generate the raw MLBAM GameDay files and the openWAR results from those files.

**Comment by beanumber** [comment]
I'm still not sure what the right thing to do on this is. Consider the inclusion of Ted Turocy's IDs, the rWAR figures from baseball-reference.com, and the fWAR numbers from FanGraphs. None of these are necessary to compute openWAR or to use our package. They also take up a fair amount of space. Thus, the purists would probably argue that they belong somewhere (e.g. the `openWARData` package).

**Comment by beanumber** [comment]
Consider also the full-season MLBAM data files. These are bigger (~10 MB), and I'm not sure if they are legal to distribute anyway, so they should probably not be in the package either. But it's hard to do anything interesting in the vignettes without loading these, since downloading new data every time you want to compile the vignettes is insane.

**Comment by beanumber** [comment]
On the other hand, including the pre-compiled openWAR results seems like a win, since those are small, relevant to what we are doing in this package, and we can do fun things with them in the vignettes.

**Comment by beanumber** [comment]
I'm closing this issue. As of now, small data files that are essential to `openWAR` are included in the package:

```
MetsBraves
May14
May
openWAR.2012
openWAR.2013
openWAR.2014
```

Larger data files that are not essential to the package have been moved to the `openWARData` package. Note that this includes both the full `MLBAM` data and the processed `openWARPlays` data for 2012-2014.

**Comment by znmeb** [comment]
@beanumber Did you ever come to a conclusion on the "legality" of redistributing the data? I'm in the final throes of releasing a Docker image with openWAR in it and I want to know if the IP folks at MLB are likely to come after me. They'll probably leave you alone - fair use and academia and all that - but hope is not a strategy, as they say. ;-)

**Comment by davidbmitchell** [comment]
Here is the copyright information: http://gdx.mlb.com/components/copyright.txt
and if you don't feel like clicking a link:
```
The accounts, descriptions, data and presentation in the referring page (the "Materials") are proprietary content of MLB Advanced Media, L.P ("MLBAM").  
Only individual, non-commercial, non-bulk use of the Materials is permitted and any other use of the Materials is prohibited without prior written authorization from MLBAM.  
Authorized users of the Materials are prohibited from using the Materials in any commercial manner other than as expressly authorized by MLBAM.
```

**Comment by znmeb** [comment]
@davidbmitchell Thanks!!

**Comment by beanumber** [comment]
@znmeb I guess it depends on your interpretation of "bulk". The full-season data sets have all been moved to the `openWARData` package, so you would probably not want to include that in your image. On the other hand `openWAR` only contains small amounts of data from MLBAM, so I hope that is OK. 

I never did get clarity on this issue.

**Comment by znmeb** [comment]
@beanumber I dropped openWARData - I don't need it for my use case, which involves a 60 megabit per second download link. ;-)
