### ISSUE TITLE
streamline dependencies

### ISSUE THREAD

**Issue by beanumber** [beanumber/openWAR#41]
Should we import all of `dplyr` or `mosaic`?

**Comment by obarisk** [comment]
Note that both packages provided "do" function,
it's better to call "do" with namespace(::).

I think it's better to use importFrom with mosaic package,
because there are not many functions come from mosaic package.

**Comment by znmeb** [comment]
Mosaic is pushing towards a CRAN release and moving things around. I'm currently using their most recent GitHub release.

**Comment by beanumber** [comment]
I made all references do `do()` explicit. There were a few for `mosaic::do()` and a few for `dplyr::do()`. 

Question: The warning message that says:

`
replacing previous import by ‘mosaic::do’ when loading ‘openWAR’ 
`
I assume this is because we import all of `dplyr`, and thus `dplyr::do`, but then also we import `mosaic::do`. Is there any way to get rid of this warning?

**Comment by znmeb** [comment]
You shouldn't get rid of the warning - you should change the code so it doesn't generate warnings ;-)

Seriously, though, wrap dplyr::do with your own function with a name based on what it does and mosaic::do with another of your own functions with a different name. It's a little more effort in the documentation but it will pay off when you run into problems.

**Comment by beanumber** [comment]
OK, I did this. I added `mosaic.do()` to the `utils.R` file. It seems a little hacky, but it seems to work.

**Comment by beanumber** [comment]
Should we import all of `lattice`? There are a number of dependencies now, and since it is a drawing library, someone might want to add options that we haven't used.

**Comment by beanumber** [comment]
I'm closing this. We can revisit this for the next version.

**Comment by beanumber** [comment]
As of 8ba4c99 we are importing all of `lattice`.
