### ISSUE TITLE
bug in results vignette when using summary.openWARPlayers

### ISSUE THREAD

**Issue by beanumber** [beanumber/openWAR#45]
```
data(openWAR.2012)
summary(openWAR.2012)
```
` 
Hide Traceback
 
 Rerun with Debug
 Error: data_frames can only contain 1d atomic vectors and lists 
13 stop("data_frames can only contain 1d atomic vectors and lists", 
    call. = FALSE) 
12 as_data_frame(data) 
11 tbl_df(.data) 
10 filter_(tbl_df(.data), .dots = dots) 
9 as.data.frame(filter_(tbl_df(.data), .dots = dots)) 
8 filter_.data.frame(.data, .dots = lazyeval::lazy_dots(...)) 
7 filter_(.data, .dots = lazyeval::lazy_dots(...)) 
6 filter(data, RAA.pitch != 0) 
5 nrow(filter(data, RAA.pitch != 0)) 
4 paste("Displaying information for", nrow(data), "players, of whom", 
    nrow(filter(data, RAA.pitch != 0)), "have pitched\n") 
3 cat(paste("Displaying information for", nrow(data), "players, of whom", 
    nrow(filter(data, RAA.pitch != 0)), "have pitched\n")) at openWARPlayers.R#28
2 summary.openWARPlayers(openWAR.2012) 
1 summary(openWAR.2012) 
`

? It's late, but I don't get what the problem is. This seems relevant:

(https://github.com/hadley/dplyr/issues/999)

**Comment by obarisk** [comment]
test this
```r
data(openWAR.2012)
openWAR.2012[1:nrow(openWAR.2012), c(1:38, 40:41)] %>% dplyr::filter(RAA.pitch!=0)
try(openWAR.2012 %>% dplyr::filter(RAA.pitch!=0))
class(openWAR.2012[, 1]) # numeric
class(openWAR.2012[, 39]) # matrix?
```

**Comment by obarisk** [comment]
In R 3.2, is it possible to store a matrix in cells of data.frame?
note that in getWAR.R
```r
players$repl = as.numeric(pt.mat %*% repl.means)
```
a side effect of `%*%` ?

**Comment by beanumber** [comment]
This was an issue with the data frames being old. I refreshed the 2012 and 2013 data and it works now. Working on 2014 now...

**Comment by beanumber** [comment]
Refreshed 2014 data and this is fixed.
