### ISSUE TITLE
should the package be named "openwaR" instead?

### ISSUE THREAD

**Issue by beanumber** [beanumber/openWAR#47]
Hadley sez:

`Avoid using both upper and lower case letters: doing so makes the package name hard to type and even harder to remember. 
Add an extra R
`
http://r-pkgs.had.co.nz/package.html

**Comment by znmeb** [comment]
I'd either stick with openWAR or switch to openwar. There's no need for the extra 'r' at the end.

**Comment by beanumber** [comment]
OK, sounds good!
