### ISSUE TITLE
updateGame funtion

### ISSUE THREAD

**Issue by gjm112** [beanumber/openWAR#48]
Do we need this function?  Why would we need to update a game?  

Does this give us something that getData doesn't?

**Comment by beanumber** [comment]
It allows you to overwrite the data from a single game without having to re-download all of the other games. This was very useful during testing. Ideally, end users wouldn't need it. \

But let's say that you try to download an entire season's worth of data, but somewhere in the middle, your Internet connection goes out for a minute. So you end up with a full season of data, but one of the games is corrupted. You can use `updateGame()` to fix that single game. 

I say we leave it for now, but maybe we can remove it later. We could move it to `utils.R`. Or we can not export it.

**Comment by gjm112** [comment]
Oh that is useful.  Leave it in.
