### ISSUE TITLE
why isn't tabulate a generic?

### ISSUE THREAD

**Issue by beanumber** [beanumber/openWAR#51]
```{r}
library(openWAR)
```
```
The following object is masked from ‘package:base’:

    tabulate
```
Why isn't `tabulate()` a generic S3 method like `plot()` and `summary()`? Do I need to add `setGeneric()` or something?

**Comment by davidbmitchell** [comment]
If I'm not mistaken it is because of this 
```r
tabulate = function(data) UseMethod("tabulate")
```
You are overriding the ```base::tabulate()```. Looking through the openWAR code there is nothing like that for ```plot()``` or ```summary()```.  So when you define the method ```tabulate.GameDayPlays```, it is a method of the generic ```openWAR::tabulate()``` not ```base::tabulate()```.

**Comment by beanumber** [comment]
But unlike `plot()` and `summary()`, `tabulate()` is not a generic function. So how do you make it an S3 generic without overriding `base::tabulate()`?

**Comment by beanumber** [comment]
I still don't understand this.

**Comment by davidbmitchell** [comment]
I think as long as we use the name ```tabulate```, it's going to override ```base::tabulate()```. I don't think there's any way around it except for changing the name of the function.

**Comment by beanumber** [comment]
Adding `@method` to the documentation for `tabulate.GameDayPlays` made this an S3 generic.

**Comment by beanumber** [comment]
This will break `base::tabulate()` so I think we should just rename this function. 
What if `tabulate.GameDayPlays()" becomes `summary.GameDayPlays()`? Is that going to screw anybody up?
