### ISSUE TITLE
documentation for gamedayplays.R

### ISSUE THREAD

**Issue by gjm112** [beanumber/openWAR#57]

**Comment by gjm112** [comment]
I get this warning when using the example plot(May, event = c("Single","Home Run"), pch = 16)

 draw.key(simpleKey(...), draw = FALSE) : not enough rows for columns

Any thoughts?

**Comment by beanumber** [comment]
In `plot.GameDayPlays()`, we have the line:
```
                  , auto.key = list(columns = 4)
```
If there are fewer than 4 outcomes, then it will generate this error. I'll fix it.
