### ISSUE TITLE
Typo in the paper?

### ISSUE THREAD

**Issue by znmeb** [beanumber/openWAR#75]
I didn't see a place on Arxiv to comment on the paper so I'll do it here. ;-)

http://arxiv.org/pdf/1312.7158v3.pdf, page 11:

"Using the convention that approximately 10 wins are equivalent to one win"

Shouldn't that be 10 runs?

**Comment by beanumber** [comment]
Yes, good catch! Unfortunately, this typo made it into the JQAS paper as well. :(

**Comment by znmeb** [comment]
Another one (page 4):

"Here, we illustrate that the expected run matrix —a common sabermetric construction dating back to the work of Lindsey (1959, 1961)—can be used to model th1ese quantities."

th1ese

**Comment by beanumber** [comment]
Thanks for sending these. Please keep sending them, but I'm closing this issue.
