### ISSUE TITLE
getWAR() seems inefficient

### ISSUE THREAD

**Issue by beanumber** [beanumber/openWAR#77]
This code will be faster with `dplyr`, and the logic looks inefficient to me, especially for the case where `dataRepl` is null.

**Comment by gjm112** [comment]
Probably true.  I made this fix mainly so we could calculate current
openWAR.  I didn't think much about it and it could definitely be improved
in terms of efficiency.

**Comment by gjm112** [comment]
I hopefully addressed the problem of inefficiency when dataRepl is NULL.  getRAA will only be called once in this case (as opposed to twice before).

**Comment by gjm112** [comment]
This is the commit that addresses this: https://github.com/beanumber/openWAR/commit/206afdc36e0061e678f537e0e70e311726dd429c
