### ISSUE TITLE
do we need GameDayPlaysExt?

### ISSUE THREAD

**Issue by beanumber** [beanumber/openWAR#80]
I don't think we ever really use this. It is one of the slots in the output of `makeWAR()`, but it is suppressed the `low.memory` flag, which is turned on by default.

**Comment by gjm112** [comment]
I was just looking at the documentation for this and, while the documentation looks fine, I agree with you in that I don't we use this very often (if at all?).

**Comment by beanumber** [comment]
Let's leave it for now. We could do something with this later, or we could remove it.
