### ISSUE TITLE
vignettes not found?

### ISSUE THREAD

**Issue by beanumber** [beanumber/openWAR#82]
```
> browseVignettes("openWAR")
No vignettes found by browseVignettes("openWAR")
```

Why not?

**Comment by gjm112** [comment]
Is that only looking at vignettes for packages that are already on CRAN?

On Tue, Jun 23, 2015 at 10:48 AM, Ben Baumer <notifications@github.com>
wrote:

> > browseVignettes("openWAR")
> No vignettes found by browseVignettes("openWAR")
>
> Why not?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beanumber/openWAR/issues/82>.
>



-- 
Gregory J. Matthews, Ph.D.
Assistant Professor
Department of Mathematics and Statistics
Loyola University Chicago
E-mail: gjm112 -at- gmail.com
Blog: StatsInTheWild.com
Art: etsy.me/1JAsYz9
Twitter: @StatsInTheWild <http://www.twitter.com/StatsInTheWild>
Twitter: @StatsClass <http://www.twitter.com/statsclass>

**Comment by gjm112** [comment]
If you do vignette("intro") it works.  We probably need more intuitive names for the vignettes.  like vignette("openWAR") maybe?

**Comment by beanumber** [comment]
That doesn't seem to be the issue, since it is supposed to work like:

```
> browseVignettes(package)
```
Also, when you go to the openWAR index page in the help menu, it doesn't like the vignettes. Somehow they are not registered.

**Comment by gjm112** [comment]
But If you do vignette("openWAR") it works.

**Comment by cpsievert** [comment]
`devtools::install_github()` calls `devtools::install()` which has a default of `build_vignettes = FALSE`, so this will fix the problem

```r
devtools::install_github("beanumber/openWAR", build_vignettes = TRUE)
browseVignettes("openWAR")
```

**Comment by beanumber** [comment]
I am still seeing this behavior even after checking the box @cpsievert mentioned. 
```
> browseVignettes(package = "openWAR")
No vignettes found by browseVignettes(package = "openWAR")
> vignette("intro", package = "openWAR")
Warning message:
vignette ‘intro’ not found 
```

**Comment by beanumber** [comment]
Ohhhh...I get it. The problem is on my end. You have to
```
devtools::build_vignettes()
```
But then if users don't use the `build_vignettes = TRUE` option, how will they see them?
