### ISSUE TITLE
fix @titles

### ISSUE THREAD

**Issue by beanumber** [beanumber/openWAR#87]
The @title field in the documentation usually doesn't say what it should:

http://r-pkgs.had.co.nz/man.html#roxygen-comments

* The first sentence becomes the title of the documentation. That’s what you see when you look at help(package = mypackage) and is shown at the top of each help file. It should fit on one line, be written in sentence case, and end in a full stop.

* The second paragraph is the description: this comes first in the documentation and should briefly describe what the function does.

* The third and subsequent paragraphs go into the details: this is a (often long) section that is shown after the argument description and should go into detail about how the function works.

**Comment by gjm112** [comment]
Done.
