### ISSUE TITLE
Incompatible with R 3.2.3 Wooden Christmas-Tree

### ISSUE THREAD

**Issue by MartnAR** [beanumber/openWAR#99]
Installed openWAR package on R 3.2.2 but when upgraded to R 3.2.3, openWAR becomes incompatible. Will there be any update on this issue?

**Comment by beanumber** [comment]
Yes, this seems like something that we can fix. Can you be more specific about the nature of the error?

**Comment by MartnAR** [comment]
Sure, the problem actually states that openWAR's incompatibilty is due to both KernSmooth and Sxslt packages are not available for R 3.2.3. 
KernSmooth has zero non exit status, which can be fixed on the linux cmd line. Sxslt on the other hand has an html line which is malformed (on omegahat.org). On the cboettig GitHub repo, Sxslt finds a fatal error when installing the converters. I'm attaching the exact error code line for Sxslt and openWAR.
Thanks! 
[R 3-2-3 Sxslt and openWAR installation errors .pdf](https://github.com/beanumber/openWAR/files/119538/R.3-2-3.Sxslt.and.openWAR.installation.errors.pdf)

**Comment by beanumber** [comment]
Aha. I think the problem is that you don't have the XSLT libraries installed. This:
```
checking for xslt-config... no
```
is a problem. Since you're using Linux this should be a easy fix. Can you install the libraries suggested [here](https://github.com/beanumber/openWAR/blob/master/.travis.yml)
```
 - libxslt1-dev
 - libxslt1.1
 - libxml2
 - libxml2-dev
```
and try again?

**Comment by znmeb** [comment]
Omegahat seems to have expired domain-wise:

![screenshot from 2016-02-05 11 26 11](https://cloud.githubusercontent.com/assets/4938/12856759/511653be-cbfb-11e5-9486-18fb19c49b3f.png)

![screenshot from 2016-02-05 11 27 25](https://cloud.githubusercontent.com/assets/4938/12856794/762b3692-cbfb-11e5-853e-1af2e7028f3e.png)

There's a version here on GitHub but it doesn't install.

**Comment by MartnAR** [comment]
Thanks znmeb! beanumber, I installed the libraries you suggested plus libblas-dev in order to install the KernSmooth package. There's still a problem with the RcppEigen package. I have it installed in my library but when downloading the openWAR package, it reloads it and states it has non-zero exit status. I loaded the library before the installation but to no avail.
I'm attaching the new error message. 
[R 3-2-3 openWAR installation error.pdf](https://github.com/beanumber/openWAR/files/119782/R.3-2-3.openWAR.installation.error.pdf)

**Comment by znmeb** [comment]
@MartnAR Looks like you don't have the header files for LAPACK installed. What OS are you running?

**Comment by beanumber** [comment]
Yikes! Well, I guess it's time to really get rid of `Sxslt`. (#23)

@MartnAR it sounds like your issue is with `RcppEigen` (and not `openWAR` directly).

**Comment by MartnAR** [comment]
@znmeb You are correct! I haven't installed lapack. I'm using Ubuntu 15.04. @beanumber, let me try and correct the issue with RcppEigen and I'll let you know if this solves the issue with openWAR. 
Thanks to both of you for your help.

**Comment by znmeb** [comment]
@beanumber Sxslt is open source - you could just grab the bits you're using into openWAR, right? ;-)

**Comment by MartnAR** [comment]
Fixed! @znmeb you were correct. Once Lapack-dev was installed, the issue with RcppEigen was fixed and openWAR was able to install correctly. 
Thanks again!

**Comment by beanumber** [comment]
@znmeb In theory, I suppose that's true. In practice, I haven't looked at their code so I'm not sure how easy that you be. It also doesn't solve the problem of having the external dependency on `libxslt`. But I suppose it would be an improvement over the current state of affairs!
